workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials # Create this group in Codemagic UI and add variables below:
        # APP_STORE_CONNECT_ISSUER_ID
        # APP_STORE_CONNECT_KEY_IDENTIFIER
        # APP_STORE_CONNECT_PRIVATE_KEY (as Secure Variable)
      vars:
        BUNDLE_ID: "com.yossy.stock"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Codemagic
        script: |
          keychain initialize
          # Fetching certificates and profiles from Apple
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=$CM_EXPORT_OPTIONS_PATH \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com # Update this

  web-release:
    name: Web Release Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Web
        script: |
          flutter build web --release --web-renderer html
    artifacts:
      - build/web/**
